import {zipSync,strToU8} from 'fflate';
import {jsPDF} from 'jspdf';
import {autoTable} from 'jspdf-autotable';
import './enhancements.css';

type Row=Record<string,unknown>;
const API=import.meta.env.VITE_API_URL||(import.meta.env.PROD?'':'http://localhost:8080');
const token=()=>sessionStorage.getItem('homeflow_token')||'';
const authHeaders=()=>({Authorization:`Bearer ${token()}`});
const escXml=(v:unknown)=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');
const clean=(v:unknown)=>String(v??'').replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,'');

async function api(path:string){const r=await fetch(`${API}${path}`,{headers:authHeaders()});if(!r.ok)throw new Error(`Unable to load report data (${r.status}).`);return r.json()}
function activeTitle(){return document.querySelector('main header h1')?.textContent?.trim()||'HomeFlow AI'}
function activeSlug(){return activeTitle().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'report'}
function fmtMoney(v:unknown){const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR',maximumFractionDigits:0}).format(n):String(v??'')}

async function reportRows():Promise<Row[]>{
 const title=activeTitle();
 if(title==='Contractors')return (await api('/api/contractors')).map((x:any)=>({Contractor:x.name,Projects:x.projects,'Average health':`${x.averageHealth}/100`,Critical:x.criticalProjects,'At risk':x.atRiskProjects,'Overdue milestones':x.overdueMilestones,'Units completed':x.unitsCompleted,'Portfolio value':fmtMoney(x.contractValue)}));
 if(title==='Risks & Blockers')return (await api('/api/risks')).map((x:any)=>({Project:x.projectName,Province:x.province,Municipality:x.municipality,Status:x.status,'Health score':`${x.healthScore}/100`,'Open risks':x.openRisks,'Primary blocker':x.primaryBlocker,'Root causes':Array.isArray(x.rootCauses)?x.rootCauses.join('; '):x.rootCauses,'Evidence age':`${x.evidenceAgeDays} days`,'Budget-progress gap':`${x.financialPhysicalDivergence} pts`}));
 if(title==='Recovery Plans')return (await api('/api/recovery')).map((x:any)=>({Project:x.projectName,Action:x.title,Owner:x.owner,Due:x.due,Status:x.status,'Project status':x.projectStatus,'Health score':`${x.healthScore}/100`}));
 if(title==='Audit & Governance')return await api('/api/audit');
 if(title==='Usage Logs')return await api('/api/usage-logs');
 const projects=await api('/api/projects');
 if(title==='Finance')return projects.map((p:any)=>({Project:p.name,Province:p.province,Contractor:p.contractor,Budget:fmtMoney(p.budget),Expenditure:fmtMoney(p.expenditure),'Spend %':Math.round(p.expenditure/p.budget*100),'Physical %':p.physicalProgress,'Divergence pts':Math.round(p.expenditure/p.budget*100)-p.physicalProgress,Status:p.status}));
 if(title==='Delivery Map'){
   const provinces=[...new Set(projects.map((p:any)=>p.province))] as string[];
   return provinces.map(province=>{const ps=projects.filter((p:any)=>p.province===province);return {Province:province,Projects:ps.length,Critical:ps.filter((p:any)=>p.status==='Critical').length,'At risk':ps.filter((p:any)=>p.status==='At Risk').length,'Average health':`${Math.round(ps.reduce((s:number,p:any)=>s+p.healthScore,0)/ps.length)}/100`,'Units completed':ps.reduce((s:number,p:any)=>s+p.unitsCompleted,0),'Portfolio budget':fmtMoney(ps.reduce((s:number,p:any)=>s+p.budget,0))}})
 }
 return projects.map((p:any)=>({Project:p.name,'Project ID':p.id,Province:p.province,Municipality:p.municipality,Contractor:p.contractor,Programme:p.programme,Status:p.status,'Health score':`${p.healthScore}/100`,Budget:fmtMoney(p.budget),Expenditure:fmtMoney(p.expenditure),'Physical progress':`${p.physicalProgress}%`,'Planned progress':`${p.plannedProgress}%`,'Units completed':`${p.unitsCompleted}/${p.unitsPlanned}`,'Overdue milestones':p.overdueMilestones,'Open risks':p.openRisks,'Primary blocker':p.primaryBlocker,'Forecast completion':p.forecastCompletion}));
}

function makeXlsx(rows:Row[],sheetName='Report'){
 const keys=Array.from(new Set(rows.flatMap(r=>Object.keys(r))));
 const rowXml=[keys,...rows.map(r=>keys.map(k=>r[k]))].map((row,ri)=>`<row r="${ri+1}">${row.map((v,ci)=>{let n=ci+1,col='';while(n){n--;col=String.fromCharCode(65+n%26)+col;n=Math.floor(n/26)}return `<c r="${col}${ri+1}" t="inlineStr"><is><t xml:space="preserve">${escXml(clean(v))}</t></is></c>`}).join('')}</row>`).join('');
 const files:Record<string,Uint8Array>={
  '[Content_Types].xml':strToU8('<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>'),
  '_rels/.rels':strToU8('<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'),
  'xl/workbook.xml':strToU8(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="${escXml(sheetName.slice(0,31))}" sheetId="1" r:id="rId1"/></sheets></workbook>`),
  'xl/_rels/workbook.xml.rels':strToU8('<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>'),
  'xl/styles.xml':strToU8('<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="1"><font><sz val="10"/><name val="Aptos"/></font></fonts><fills count="1"><fill><patternFill patternType="none"/></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/></cellXfs></styleSheet>'),
  'xl/worksheets/sheet1.xml':strToU8(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><sheetFormatPr defaultRowHeight="16"/><sheetData>${rowXml}</sheetData><autoFilter ref="A1:${String.fromCharCode(64+Math.min(keys.length,26))}${rows.length+1}"/></worksheet>`)
 };
 return new Blob([zipSync(files,{level:6})],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});
}
function saveBlob(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function exportExcel(){try{const rows=await reportRows();if(!rows.length)throw new Error('No report records are available.');saveBlob(makeXlsx(rows,activeTitle()),`HomeFlow-${activeSlug()}-${new Date().toISOString().slice(0,10)}.xlsx`);logExport('Downloaded Excel report')}catch(e:any){alert(e?.message||'Unable to generate Excel report.')}}
async function exportPdf(){try{const rows=await reportRows();if(!rows.length)throw new Error('No report records are available.');const keys=Object.keys(rows[0]);const doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'});doc.setFontSize(16);doc.text(`HomeFlow AI - ${activeTitle()}`,14,14);doc.setFontSize(8);doc.setTextColor(90);doc.text(`Generated ${new Date().toLocaleString('en-ZA')} | Synthetic demo data`,14,20);autoTable(doc,{startY:25,head:[keys],body:rows.map(r=>keys.map(k=>clean(r[k]))),theme:'grid',styles:{fontSize:6,cellPadding:1.5,overflow:'linebreak'},headStyles:{fillColor:[15,32,48],textColor:[255,255,255]},alternateRowStyles:{fillColor:[244,247,250]},margin:{left:8,right:8,bottom:10}});doc.save(`HomeFlow-${activeSlug()}-${new Date().toISOString().slice(0,10)}.pdf`);logExport('Downloaded PDF report')}catch(e:any){alert(e?.message||'Unable to generate PDF report.')}}
function logExport(action:string){fetch(`${API}/api/usage/events`,{method:'POST',headers:{...authHeaders(),'Content-Type':'application/json'},body:JSON.stringify({action,target:activeTitle()})}).catch(()=>{})}

function addReportButtons(){const actions=document.querySelector('.header-actions');if(!actions||actions.querySelector('[data-hf-report="excel"]'))return;const old=[...actions.querySelectorAll('button')].find(b=>/download report/i.test(b.textContent||'')) as HTMLButtonElement|undefined;if(old)old.style.display='none';const excel=document.createElement('button');excel.className='ghost hf-report-button';excel.dataset.hfReport='excel';excel.textContent='Excel';excel.title='Download the current HomeFlow report in Excel format';excel.onclick=exportExcel;const pdf=document.createElement('button');pdf.className='ghost hf-report-button';pdf.dataset.hfReport='pdf';pdf.textContent='PDF';pdf.title='Download the current HomeFlow report in PDF format';pdf.onclick=exportPdf;const anchor=old||actions.firstElementChild;anchor?.insertAdjacentElement('afterend',pdf);anchor?.insertAdjacentElement('afterend',excel)}

async function ensureRiskFallback(){if(activeTitle()!=='Risks & Blockers')return;const head=[...document.querySelectorAll('.card-head h2')].find(x=>x.textContent?.trim()==='Risks & Blockers');const card=head?.closest('.card');const host=card?.querySelector('.data-cards') as HTMLElement|null;if(!host||host.querySelector('.data-card,.hf-risk-fallback,.loading-view'))return;if(host.dataset.hfRiskLoading==='1')return;host.dataset.hfRiskLoading='1';await new Promise(r=>setTimeout(r,450));if(host.querySelector('.data-card')){delete host.dataset.hfRiskLoading;return}try{const risks=await api('/api/risks');if(!Array.isArray(risks)||!risks.length){host.innerHTML='<div class="empty-state hf-risk-fallback"><b>No risks or blockers</b><p>No active risk records are visible to your role.</p></div>';return}host.innerHTML='';for(const x of risks){const wrap=document.createElement('div');wrap.className='hf-risk-fallback';wrap.innerHTML=`<button class="data-card clickable-card hf-risk-card"><div class="data-card-top"><b>${escXml(x.projectName)}</b><span class="status ${String(x.status||'').toLowerCase().replaceAll(' ','-')}">${escXml(x.status)}</span></div><p>${escXml(x.primaryBlocker)}</p><small>${escXml(x.openRisks)} open risks · evidence ${escXml(x.evidenceAgeDays)} days old</small><em>${escXml(x.financialPhysicalDivergence)} pt budget/progress divergence</em></button><div class="hf-risk-detail" hidden><div><span>Province</span><b>${escXml(x.province)}</b></div><div><span>Municipality</span><b>${escXml(x.municipality)}</b></div><div><span>Health</span><b>${escXml(x.healthScore)}/100</b></div><div><span>Root causes</span><b>${escXml(Array.isArray(x.rootCauses)?x.rootCauses.join(', '):x.rootCauses||'Not recorded')}</b></div></div>`;const btn=wrap.querySelector('button')!;const detail=wrap.querySelector('.hf-risk-detail') as HTMLElement;btn.addEventListener('click',()=>{detail.hidden=!detail.hidden});host.appendChild(wrap)}}catch(e:any){host.innerHTML=`<div class="empty-state hf-risk-fallback"><b>Unable to display risks</b><p>${escXml(e?.message||'Please try again.')}</p></div>`}finally{delete host.dataset.hfRiskLoading}}

let riskTimer:number|undefined;
function enhance(){addReportButtons();if(activeTitle()==='Risks & Blockers'){window.clearTimeout(riskTimer);riskTimer=window.setTimeout(ensureRiskFallback,300)}}
const observer=new MutationObserver(enhance);observer.observe(document.documentElement,{subtree:true,childList:true});window.addEventListener('load',enhance);setTimeout(enhance,300);
