import React,{useEffect,useMemo,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{Activity,AlertTriangle,BarChart3,Bot,Building2,ChevronRight,CircleDollarSign,ClipboardList,FileCheck2,Gauge,Home,KeyRound,Languages,LockKeyhole,LogOut,MapPinned,Mic,Search,Settings,ShieldCheck,Sparkles,Users,VolumeX,X}from'lucide-react';
import'./styles.css';
import'./homeflow-overrides.css';

type Project={id:string;name:string;province:string;municipality:string;contractor:string;programme:string;status:string;healthScore:number;confidence:number;budget:number;expenditure:number;physicalProgress:number;plannedProgress:number;unitsPlanned:number;unitsCompleted:number;overdueMilestones:number;openRisks:number;evidenceAgeDays:number;forecastCompletion:string;primaryBlocker:string;trend:string;rootCauses:string[];projectManager:string;implementingAgent:string;ward:string;stage:string;startDate:string;recoveryActions:any[];activity:any[]};
type Dashboard={totalProjects:number;critical:number;atRisk:number;watch:number;onTrack:number;completed:number;unitsPlanned:number;unitsCompleted:number;budget:number;expenditure:number;overdueMilestones:number;openRisks:number;averagePhysicalProgress:number;highDivergenceProjects:number};
type User={id:string;name:string;email:string;role:string;province?:string;organization?:string;permissions:string[]};
type View='command'|'projects'|'map'|'contractors'|'finance'|'risks'|'recovery'|'audit'|'usage';
type ChatMsg={role:'user'|'assistant';text:string};
type Model='gpt-5.6-luna'|'gpt-5.6-terra'|'gpt-5.6-sol';
type Detail={type:'project'|'contractor'|'province'|'brief'|'message';key:string;title:string;data:any}|null;

const API=import.meta.env.VITE_API_URL||(import.meta.env.PROD?'':'http://localhost:8080');
const currency=(n:number)=>new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR',maximumFractionDigits:0}).format(n);
const statusClass=(s:string)=>s.toLowerCase().replaceAll(' ','-');
const voiceLanguages=[['en-ZA','English (South Africa)'],['af-ZA','Afrikaans'],['zu-ZA','isiZulu'],['xh-ZA','isiXhosa'],['st-ZA','Sesotho'],['tn-ZA','Setswana'],['nso-ZA','Sepedi'],['ts-ZA','gitsonga'],['ve-ZA','Tshivenda'],['ss-ZA','siSwati'],['nr-ZA','isiNdebele']];
const demoAccounts=[['admin@homeflow.ai','Administrator'],['executive@homeflow.ai','National Executive'],['manager@homeflow.ai','Gauteng Programme Manager'],['inspector@homeflow.ai','Site Inspector'],['contractor@homeflow.ai','Contractor']];
const navItems:Array<[View,string,any]>=[['command','Command Centre',Gauge],['projects','Projects',Building2],['map','Delivery Map',MapPinned],['contractors','Contractors',Users],['finance','Finance',CircleDollarSign],['risks','Risks & Blockers',AlertTriangle],['recovery','Recovery Plans',Activity],['audit','Audit & Governance',ShieldCheck],['usage','Usage Logs',ClipboardList]];
const roleViews:Record<string,View[]>={Administrator:['command','projects','map','contractors','finance','risks','recovery','audit','usage'],'National Executive':['command','projects','map','contractors','finance','risks','recovery','audit','usage'],'Provincial Programme Manager':['command','projects','map','contractors','finance','risks','recovery'],'Site Inspector':['command','projects','map','risks'],'Contractor':['command','projects','recovery']};
const provincePoints:Record<string,[number,number]>={'Western Cape':[185,415],'Northern Cape':[265,275],'Eastern Cape':[400,410],'Free State':[385,300],'North West':[350,220],'Gauteng':[430,205],'Limpopo':[475,120],'Mpumalanga':[515,220],'KwaZulu-Natal':[525,345]};

function Metric({label,value,icon:Icon,tone='blue'}:{label:string;value:React.ReactNode;icon:any;tone?:string}){return <div className="metric"><div className={`metric-icon ${tone}`}><Icon size={19}/></div><div><small>{label}</small><strong>{value}</strong></div></div>}
function Status({value}:{value:string}){return <span className={`status ${statusClass(value)}`}>{value}</span>}
function Info({label,value}:{label:string;value:any}){return <div className="info"><span>{label}</span><b>{value}</b></div>}

function Login({onLogin}:{onLogin:(token:string,user:User)=>void}){
 const[email,setEmail]=useState('admin@homeflow.ai');const[password,setPassword]=useState('HomeFlow!2026');const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch(`${API}/api/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Login failed');sessionStorage.setItem('homeflow_token',b.token);sessionStorage.setItem('homeflow_user',JSON.stringify(b.user));onLogin(b.token,b.user)}catch(e:any){setError(e.message||'Login failed')}finally{setBusy(false)}}
 return <div className="login-page"><div className="login-glow"></div><section className="login-card"><div className="login-brand"><img src="/pyrneo-logo.png" className="login-logo" alt="Pyrneo"/><div className="product-name login-product">HomeFlow AI</div></div><p className="eyebrow">HUMAN SETTLEMENTS DELIVERY ASSURANCE</p><h1>Secure Delivery Intelligence</h1><p className="login-copy">Access the HomeFlow Command Centre, project intelligence, recovery workflows and conversational delivery copilot.</p><form onSubmit={submit}><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email"/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password"/></label>{error&&<div className="login-error">{error}</div>}<button className="login-submit" disabled={busy}><LockKeyhole size={18}/>{busy?'Signing in…':'Sign in'}</button></form><div className="demo-accounts"><b>Hackathon demo access</b><span>Password for all demo accounts: <code>HomeFlow!2026</code></span>{demoAccounts.map(([e,r])=><button key={e} onClick={()=>setEmail(e)}><span>{r}</span><small>{e}</small></button>)}</div><small className="demo-note">Synthetic demonstration data only. Production identity is designed for Microsoft Entra ID.</small></section></div>
}

function App(){
 const[token,setToken]=useState(()=>sessionStorage.getItem('homeflow_token')||'');
 const[user,setUser]=useState<User|null>(()=>{try{return JSON.parse(sessionStorage.getItem('homeflow_user')||'null')}catch{return null}});
 const[projects,setProjects]=useState<Project[]>([]);const[dashboard,setDashboard]=useState<Dashboard|null>(null);const[selected,setSelected]=useState<Project|null>(null);const[view,setView]=useState<View>('command');const[query,setQuery]=useState('');const[viewData,setViewData]=useState<any[]>([]);const[viewLoading,setViewLoading]=useState(false);const[detail,setDetail]=useState<Detail>(null);
 const[settingsOpen,setSettingsOpen]=useState(false);const[chatOpen,setChatOpen]=useState(false);const[messages,setMessages]=useState<ChatMsg[]>([{role:'assistant',text:'Hello. I am your HomeFlow delivery copilot. We can have a full conversation about the projects visible to your role. Ask me what needs attention, why a project is at risk, what changed, or what action to take next.'}]);const[chatInput,setChatInput]=useState('');const[busy,setBusy]=useState(false);const[listening,setListening]=useState(false);const[provider,setProvider]=useState('rules');
 const[apiKey,setApiKey]=useState(()=>sessionStorage.getItem('homeflow_openai_key')||'');const[model,setModel]=useState<Model>(()=>(localStorage.getItem('homeflow_model')as Model)||'gpt-5.6-luna');const[voiceLang,setVoiceLang]=useState(()=>localStorage.getItem('homeflow_voice_lang')||'en-ZA');const[autoSpeak,setAutoSpeak]=useState(()=>localStorage.getItem('homeflow_auto_speak')!=='false');const[connection,setConnection]=useState('untested');const[connectionMessage,setConnectionMessage]=useState('');
 const audioRef=useRef<HTMLAudioElement|null>(null);const chatEndRef=useRef<HTMLDivElement|null>(null);const allowed=roleViews[user?.role||'']||[];
 const authHeaders=(json=true)=>{const h:Record<string,string>={Authorization:`Bearer ${token}`};if(json)h['Content-Type']='application/json';return h};
 const aiHeaders=()=>{const h=authHeaders();if(user?.role==='Administrator'&&apiKey)h['x-openai-api-key']=apiKey;return h};
 async function fetchJson(url:string,init?:RequestInit){const r=await fetch(url,{...init,headers:{...authHeaders(!init||init.method!=='GET'),...(init?.headers||{})}});if(r.status===401){logout(false);throw new Error('Session expired. Please sign in again.')}const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||String(r.status));return b}
 function login(t:string,u:User){setToken(t);setUser(u)}
 function logout(call=true){if(call&&token)fetch(`${API}/api/auth/logout`,{method:'POST',headers:authHeaders()}).catch(()=>{});sessionStorage.removeItem('homeflow_token');sessionStorage.removeItem('homeflow_user');sessionStorage.removeItem('homeflow_openai_key');setToken('');setUser(null);setProjects([]);setDashboard(null);setDetail(null)}
 async function logEvent(action:string,target:string){if(!token)return;fetch(`${API}/api/usage/events`,{method:'POST',headers:authHeaders(),body:JSON.stringify({action,target})}).catch(()=>{})}
 function navigate(v:View){if(!allowed.includes(v))return;setView(v);setDetail(null);logEvent('Opened page',navItems.find(n=>n[0]===v)?.[1]||v)}
 useEffect(()=>{if(!token||!user)return;Promise.all([fetchJson(`${API}/api/projects`,{method:'GET'}),fetchJson(`${API}/api/dashboard`,{method:'GET'})]).then(([p,d])=>{setProjects(p);setDashboard(d);setSelected(p[0]||null)}).catch(()=>{})},[token,user?.id]);
 useEffect(()=>{if(!token||!['contractors','risks','recovery','audit','usage'].includes(view))return;setViewLoading(true);const ep=view==='usage'?'usage-logs':view==='recovery'?'recovery':view;fetchJson(`${API}/api/${ep}`,{method:'GET'}).then(setViewData).catch(()=>setViewData([])).finally(()=>setViewLoading(false))},[view,token]);
 useEffect(()=>{chatEndRef.current?.scrollIntoView({behavior:'smooth'})},[messages,busy,chatOpen]);
 const filtered=useMemo(()=>projects.filter(p=>`${p.name} ${p.id} ${p.province} ${p.municipality} ${p.contractor}`.toLowerCase().includes(query.toLowerCase())),[projects,query]);
 if(!token||!user)return <Login onLogin={login}/>;
 function stopVoice(){if(audioRef.current){audioRef.current.pause();audioRef.current.src='';audioRef.current=null}if('speechSynthesis'in window)speechSynthesis.cancel()}
 async function speakText(text:string){if(!autoSpeak||!text)return;stopVoice();try{const r=await fetch(`${API}/api/voice/speak`,{method:'POST',headers:aiHeaders(),body:JSON.stringify({text,language:voiceLang})});if(r.ok){const blob=await r.blob();const url=URL.createObjectURL(blob);const a=new Audio(url);audioRef.current=a;a.onended=()=>{URL.revokeObjectURL(url);audioRef.current=null};await a.play();return}}catch{}if(!('speechSynthesis'in window))return;const u=new SpeechSynthesisUtterance(text.replace(/[*#`]/g,''));u.lang=voiceLang;u.rate=.96;u.pitch=1;const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>v.lang.toLowerCase()===voiceLang.toLowerCase())||voices.find(v=>v.lang.toLowerCase().startsWith(voiceLang.split('-')[0].toLowerCase()))||null;speechSynthesis.speak(u)}
 function explicitNavigation(q:string){return /^(open|show|go to|view)\b/i.test(q)}
 function projectMention(q:string){const id=q.match(/HF-\d+/i)?.[0];if(id){const p=projects.find(x=>x.id.toLowerCase()===id.toLowerCase());if(p)return p}const lower=q.toLowerCase();return projects.find(p=>lower.includes(p.name.toLowerCase())||lower.includes(p.name.toLowerCase().split(' ').slice(0,3).join(' ')))}
 async function sendChat(raw:string,fromVoice=false){const q=raw.trim();if(!q||busy)return;setChatOpen(true);setMessages(m=>[...m,{role:'user',text:q}]);setBusy(true);try{
   if(explicitNavigation(q)){const handled=await handleNavigation(q,fromVoice);if(handled)return}
   const mentioned=projectMention(q);const contextProject=mentioned||selected;const recent=messages.slice(-6).map(m=>`${m.role==='user'?'User':'Assistant'}: ${m.text}`).join('\n');const question=recent?`Conversation so far:\n${recent}\n\nCurrent user request: ${q}`:q;
   const r=await fetch(`${API}/api/ai/copilot`,{method:'POST',headers:aiHeaders(),body:JSON.stringify({question,projectId:contextProject?.id,model})});const b=await r.json().catch(()=>({}));if(r.status===401){logout(false);throw new Error('Session expired.')}if(!r.ok)throw new Error(b.error||`HomeFlow AI request failed (${r.status})`);const next=b.answer||'I do not have enough grounded information to answer that yet.';setProvider(b.provider||'rules');setMessages(m=>[...m,{role:'assistant',text:next}]);if(fromVoice||autoSpeak)await speakText(next)
 }catch(e:any){const next=e?.message||'I could not reach the HomeFlow AI service. Please try again.';setMessages(m=>[...m,{role:'assistant',text:next}])}finally{setBusy(false)}}
 async function handleNavigation(text:string,fromVoice=false){const q=text.trim();const lower=q.toLowerCase();const nav:Array<[RegExp,View]>=[[/^(open|show|go to|view) (the )?(command centre|dashboard|home)$/i,'command'],[/^(open|show|go to|view) (the )?projects?$/i,'projects'],[/^(open|show|go to|view) (the )?(delivery )?map$/i,'map'],[/^(open|show|go to|view) (the )?contractors?$/i,'contractors'],[/^(open|show|go to|view) (the )?finance$/i,'finance'],[/^(open|show|go to|view) (the )?(risks|risks and blockers|blockers)$/i,'risks'],[/^(open|show|go to|view) (the )?(recovery|recovery plans?)$/i,'recovery'],[/^(open|show|go to|view) (the )?(usage|usage logs?)$/i,'usage']];for(const[re,v]of nav){if(re.test(q)&&allowed.includes(v)){navigate(v);const a=`Opening ${navItems.find(x=>x[0]===v)?.[1]}.`;setMessages(m=>[...m,{role:'assistant',text:a}]);if(fromVoice)await speakText(a);return true}}
   if(/^(open|show|view|generate|read) (the )?executive brief$/i.test(q)){await loadBrief();const a='The Executive Brief is open below the header.';setMessages(m=>[...m,{role:'assistant',text:a}]);if(fromVoice)await speakText(a);return true}
   const province=['Gauteng','KwaZulu-Natal','Limpopo','Eastern Cape','Free State','Western Cape','Mpumalanga','North West','Northern Cape'].find(x=>lower.includes(x.toLowerCase()));if(province){navigate('map');await openProvince(province);const a=`Showing ${province} delivery status.`;setMessages(m=>[...m,{role:'assistant',text:a}]);if(fromVoice)await speakText(a);return true}
   const p=projectMention(q);if(p){setSelected(p);setDetail({type:'project',key:p.id,title:p.name,data:p});const a=`Opening ${p.name}.`;setMessages(m=>[...m,{role:'assistant',text:a}]);if(fromVoice)await speakText(a);return true}
   return false}
 async function loadBrief(){try{const b=await fetchJson(`${API}/api/executive-brief`,{method:'GET'});setDetail({type:'brief',key:'executive-brief',title:'Executive Brief',data:b})}catch(e:any){setDetail({type:'message',key:'brief-error',title:'Executive Brief',data:{message:e.message}})}}
 function toggleProject(p:Project){setSelected(p);setDetail(d=>d?.type==='project'&&d.key===p.id?null:{type:'project',key:p.id,title:p.name,data:p});logEvent('Opened project detail',p.name)}
 async function openProvince(name:string){try{const d=await fetchJson(`${API}/api/provinces/${encodeURIComponent(name)}`,{method:'GET'});setDetail(x=>x?.type==='province'&&x.key===name?null:{type:'province',key:name,title:name,data:d})}catch(e:any){setDetail({type:'message',key:name,title:name,data:{message:e.message}})}}
 async function openContractor(name:string){try{const d=await fetchJson(`${API}/api/contractors/${encodeURIComponent(name)}`,{method:'GET'});setDetail(x=>x?.type==='contractor'&&x.key===name?null:{type:'contractor',key:name,title:name,data:d})}catch(e:any){setDetail({type:'message',key:name,title:name,data:{message:e.message}})}}
 function startVoice(){const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){setChatOpen(true);setMessages(m=>[...m,{role:'assistant',text:'Voice recognition is not available in this browser. Chrome or Edge generally provide the broadest Web Speech support.'}]);return}stopVoice();const r=new SR();r.lang=voiceLang;r.interimResults=false;r.continuous=false;r.onstart=()=>setListening(true);r.onend=()=>setListening(false);r.onerror=()=>{setListening(false);setChatOpen(true);setMessages(m=>[...m,{role:'assistant',text:'I could not capture that voice request. Please try again.'}])};r.onresult=(e:any)=>sendChat(e.results[0][0].transcript,true);r.start()}
 async function testOpenAI(){if(user.role!=='Administrator')return;if(!apiKey){setConnection('error');setConnectionMessage('Enter an OpenAI API key first.');return}setConnection('testing');setConnectionMessage('Testing connection…');try{const r=await fetch(`${API}/api/openai/test`,{method:'POST',headers:aiHeaders(),body:JSON.stringify({model})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Connection failed');setConnection('ok');setConnectionMessage(b.message||'Connection successful.')}catch(e:any){setConnection('error');setConnectionMessage(e.message||'Connection failed')}}
 return <div className="app-shell"><aside className="sidebar"><div className="brand brand-stacked"><img src="/pyrneo-logo.png" alt="Pyrneo"/><div className="product-name">HomeFlow AI</div></div><nav>{navItems.filter(([id])=>allowed.includes(id)).map(([id,label,Icon])=><button key={id} className={view===id?'active':''} onClick={()=>navigate(id)}><Icon/>{label}</button>)}</nav>{user.role==='Administrator'&&<button className="settings-nav" onClick={()=>setSettingsOpen(true)}><Settings size={17}/> AI & Voice Settings</button>}<div className="sidebar-user"><div><b>{user.name}</b><span>{user.role}</span></div><button onClick={()=>logout()} title="Sign out"><LogOut size={17}/></button></div><div className="sidebar-note"><Sparkles size={16}/><div><b>Responsible AI</b><span>Recommendations require accountable human review.</span></div></div></aside><main className="main"><header><div><p className="eyebrow">{view==='command'?'HOMEFLOW COMMAND CENTRE':view.toUpperCase()}</p><h1>{view==='command'?'Human Settlements Delivery Assurance':navItems.find(n=>n[0]===view)?.[1]}</h1></div><div className="header-actions"><label className="lang-select"><Languages size={15}/><select value={voiceLang} onChange={e=>{setVoiceLang(e.target.value);localStorage.setItem('homeflow_voice_lang',e.target.value)}}>{voiceLanguages.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label>{user.role==='Administrator'&&<button className="ghost" onClick={()=>setSettingsOpen(true)}><KeyRound size={16}/> OpenAI</button>}<button className="ghost" onClick={loadBrief}><Sparkles size={17}/> Executive brief</button><button className={`voice ${listening?'live':''}`} onClick={startVoice}><Mic size={18}/>{listening?'Listening…':'Voice Agent'}</button></div></header>
 {detail?.type==='brief'&&<InlineDetail detail={detail} close={()=>setDetail(null)} toggleProject={toggleProject}/>} {detail?.type==='message'&&<InlineDetail detail={detail} close={()=>setDetail(null)} toggleProject={toggleProject}/>} 
 {view==='command'&&<CommandCentre dashboard={dashboard} projects={filtered} selected={selected} setSelected={setSelected} query={query} setQuery={setQuery} ask={sendChat} toggleProject={toggleProject} detail={detail}/>} 
 {view==='projects'&&<ProjectsView projects={filtered} query={query} setQuery={setQuery} toggleProject={toggleProject} detail={detail}/>} 
 {view==='map'&&<MapView projects={projects} openProvince={openProvince} detail={detail} toggleProject={toggleProject}/>} 
 {view==='finance'&&<FinanceView projects={projects} toggleProject={toggleProject} detail={detail}/>} 
 {view==='contractors'&&<ContractorsView data={viewData} loading={viewLoading} openContractor={openContractor} detail={detail} toggleProject={toggleProject}/>} 
 {view==='risks'&&<RisksView data={viewData} loading={viewLoading} projects={projects} toggleProject={toggleProject} detail={detail}/>} 
 {view==='recovery'&&<RecoveryView data={viewData} loading={viewLoading} projects={projects} toggleProject={toggleProject} detail={detail}/>} 
 {view==='audit'&&<AuditView data={viewData} loading={viewLoading}/>} {view==='usage'&&<UsageView data={viewData} loading={viewLoading}/>}<footer><span>HomeFlow AI</span><span>From stalled projects to completed homes.</span><span>{user.role} · Synthetic demo data</span></footer></main>
 <button className="chat-fab" onClick={()=>setChatOpen(true)}><Bot size={23}/><span>Ask HomeFlow</span></button>{chatOpen&&<ChatPanel messages={messages} input={chatInput} setInput={setChatInput} busy={busy} provider={provider} onSend={()=>{const q=chatInput;setChatInput('');sendChat(q,false)}} onQuick={(q:string)=>sendChat(q,false)} onVoice={startVoice} onClose={()=>setChatOpen(false)} onStop={stopVoice} endRef={chatEndRef}/>} {settingsOpen&&user.role==='Administrator'&&<SettingsPanel apiKey={apiKey} setApiKey={(v:string)=>{setApiKey(v);v?sessionStorage.setItem('homeflow_openai_key',v):sessionStorage.removeItem('homeflow_openai_key');setConnection('untested')}} model={model} setModel={(v:Model)=>{setModel(v);localStorage.setItem('homeflow_model',v)}} autoSpeak={autoSpeak} setAutoSpeak={(v:boolean)=>{setAutoSpeak(v);localStorage.setItem('homeflow_auto_speak',String(v));if(!v)stopVoice()}} connection={connection} message={connectionMessage} test={testOpenAI} close={()=>setSettingsOpen(false)}/>}</div>
}

function CommandCentre({dashboard,projects,selected,setSelected,query,setQuery,ask,toggleProject,detail}:any){return <><section className="hero"><div><b><span className="pulse-dot"></span>Delivery intelligence is active</b><p>Monitor → Anticipate → Explain → Act → Escalate → Verify → Learn</p></div><button onClick={()=>ask('What requires my attention today?')}><Sparkles size={16}/> What requires attention today?</button></section><section className="metrics"><Metric label="Projects" value={dashboard?.totalProjects??'—'} icon={Building2}/><Metric label="Critical" value={dashboard?.critical??'—'} icon={AlertTriangle} tone="red"/><Metric label="At Risk" value={dashboard?.atRisk??'—'} icon={Activity} tone="amber"/><Metric label="Units completed" value={(dashboard?.unitsCompleted??0).toLocaleString()} icon={Home} tone="green"/><Metric label="Overdue milestones" value={dashboard?.overdueMilestones??'—'} icon={FileCheck2} tone="amber"/><Metric label="Open risks" value={dashboard?.openRisks??'—'} icon={ShieldCheck} tone="red"/></section><section className="workspace"><Portfolio projects={projects} selected={selected} setSelected={setSelected} query={query} setQuery={setQuery}/><div className="insight card"><div className="card-head"><div><h2>Priority project intelligence</h2><p>Project names and delivery health drive the analysis.</p></div><Gauge/></div>{selected?<ProjectInsight p={selected} ask={ask} toggleProject={toggleProject}/>:<div className="empty-state">Select a project.</div>}</div></section>{detail?.type==='project'&&<InlineDetail detail={detail} close={()=>toggleProject(detail.data)} toggleProject={toggleProject}/>}</>}
function Portfolio({projects,selected,setSelected,query,setQuery}:any){return <section className="card"><div className="card-head"><div><h2>Portfolio priorities</h2><p>Analysis prioritises project names and delivery health.</p></div><div className="search"><Search size={15}/><input placeholder="Search project, province or contractor…" value={query} onChange={e=>setQuery(e.target.value)}/></div></div><div className="project-list">{[...projects].sort((a,b)=>a.healthScore-b.healthScore).map((p:any)=><button className={`project-row ${selected?.id===p.id?'selected':''}`} key={p.id} onClick={()=>setSelected(p)}><span className={`score ${statusClass(p.status)}`}>{p.healthScore}</span><span className="project-main"><b>{p.name}</b><span>{p.province} · {p.municipality} · {p.contractor}</span></span><span className="mini"><span>Physical</span><b>{p.physicalProgress}%</b></span><span className="mini"><span>Spend</span><b>{Math.round(p.expenditure/p.budget*100)}%</b></span><Status value={p.status}/><ChevronRight size={16}/></button>)}</div></section>}
function ProjectInsight({p,ask,toggleProject}:{p:Project;ask:(q:string)=>void;toggleProject:(p:Project)=>void}){const spend=Math.round(p.expenditure/p.budget*100),gap=spend-p.physicalProgress;return <div className="project-insight"><div className="health"><div className={`health-ring ${statusClass(p.status)}`}><strong>{p.healthScore}</strong><span>/100</span></div><div><b>{p.name}</b><span>{p.status} · {Math.round(p.confidence*100)}% confidence · {p.trend}</span></div></div><div className="bars"><label>Budget expenditure <b>{spend}%</b></label><div><i style={{width:`${spend}%`}}></i></div><label>Physical progress <b>{p.physicalProgress}%</b></label><div><i className="physical" style={{width:`${p.physicalProgress}%`}}></i></div></div><div className={`divergence ${gap>15?'danger':''}`}><BarChart3 size={18}/><div><b>{gap} pt divergence</b><span>{currency(p.expenditure)} spent of {currency(p.budget)}</span></div></div><div className="facts"><div><span>Overdue milestones</span><b>{p.overdueMilestones}</b></div><div><span>Open risks</span><b>{p.openRisks}</b></div><div><span>Evidence age</span><b>{p.evidenceAgeDays}d</b></div><div><span>Units completed</span><b>{p.unitsCompleted}/{p.unitsPlanned}</b></div></div><div className="blocker"><span>Primary blocker</span><b>{p.primaryBlocker}</b></div><div className="insight-actions three"><button onClick={()=>ask(`Why is ${p.name} at risk?`)}>Why this score?</button><button onClick={()=>ask(`What should we do next for ${p.name}?`)}>Recommended action</button><button onClick={()=>toggleProject(p)}>More details</button></div></div>}

function ProjectsView({projects,query,setQuery,toggleProject,detail}:any){return <section className="card full-view"><div className="card-head"><div><h2>Human Settlements Projects</h2><p>{projects.length} projects visible to your role. Select a record to expand its detail directly below.</p></div><div className="search wide"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search projects…"/></div></div><div className="data-table project-table"><div className="table-row header"><span>Project</span><span>Province</span><span>Contractor</span><span>Health</span><span>Status</span></div>{projects.map((p:Project)=><React.Fragment key={p.id}><button className={`table-row clickable ${detail?.type==='project'&&detail.key===p.id?'expanded-row':''}`} onClick={()=>toggleProject(p)}><span><b>{p.name}</b><small>{p.id} · {p.programme}</small></span><span>{p.province}</span><span>{p.contractor}</span><span>{p.healthScore}/100</span><span><Status value={p.status}/></span></button>{detail?.type==='project'&&detail.key===p.id&&<InlineDetail detail={detail} close={()=>toggleProject(p)} toggleProject={toggleProject}/>}</React.Fragment>)}</div></section>}

function MapView({projects,openProvince,detail,toggleProject}:any){const provinces=Array.from(new Set(projects.map((p:Project)=>p.province))) as string[];return <section className="map-layout"><div className="card map-card"><div className="card-head"><div><h2>South Africa Delivery Map</h2><p>Select a province for its full delivery status.</p></div><MapPinned/></div><div className="sa-svg-wrap"><svg viewBox="0 0 650 520" className="sa-svg"><path className="country" d="M112 170 L170 118 L252 82 L356 72 L449 88 L526 128 L580 194 L590 284 L554 365 L496 427 L410 463 L310 468 L214 440 L143 385 L101 306 L92 232 Z"/><path className="coast" d="M112 170 L170 118 L252 82 L356 72 L449 88 L526 128 L580 194 L590 284 L554 365 L496 427 L410 463 L310 468 L214 440 L143 385 L101 306 L92 232 Z"/><circle className="lesotho" cx="455" cy="365" r="24"/><text x="455" y="369" textAnchor="middle" className="lesotho-label">LS</text>{provinces.map(prov=>{const[x,y]=provincePoints[prov]||[320,260];const ps=projects.filter((p:Project)=>p.province===prov);const worst=[...ps].sort((a,b)=>a.healthScore-b.healthScore)[0];return <g key={prov} className={`province-node ${statusClass(worst?.status||'Healthy')}`} onClick={()=>openProvince(prov)}><circle cx={x} cy={y} r="28"/><text x={x} y={y-2} textAnchor="middle" className="pin-count">{ps.length}</text><text x={x} y={y+44} textAnchor="middle" className="pin-label">{prov}</text></g>})}</svg></div>{detail?.type==='province'&&<InlineDetail detail={detail} close={()=>openProvince(detail.key)} toggleProject={toggleProject}/>}</div><div className="card map-side"><div className="card-head"><div><h2>Provincial delivery status</h2><p>Click a province for full detail.</p></div></div>{provinces.map(prov=>{const ps=projects.filter((p:Project)=>p.province===prov),score=Math.round(ps.reduce((s:number,p:Project)=>s+p.healthScore,0)/ps.length),critical=ps.filter((p:Project)=>p.status==='Critical').length;return <button className={`region-row ${detail?.type==='province'&&detail.key===prov?'active-region':''}`} key={prov} onClick={()=>openProvince(prov)}><span><b>{prov}</b><small>{ps.length} projects · {critical} critical</small></span><strong>{score}/100</strong></button>})}</div></section>}

function FinanceView({projects,toggleProject,detail}:any){return <section className="card full-view"><div className="card-head"><div><h2>Budget vs Physical Progress</h2><p>Select a row to expand project detail directly below it.</p></div><CircleDollarSign/></div><div className="data-table"><div className="table-row header"><span>Project</span><span>Budget</span><span>Spend</span><span>Physical</span><span>Divergence</span></div>{[...projects].sort((a,b)=>(b.expenditure/b.budget*100-b.physicalProgress)-(a.expenditure/a.budget*100-a.physicalProgress)).map((p:Project)=>{const spend=Math.round(p.expenditure/p.budget*100),d=spend-p.physicalProgress;return <React.Fragment key={p.id}><button className={`table-row clickable ${detail?.type==='project'&&detail.key===p.id?'expanded-row':''}`} onClick={()=>toggleProject(p)}><span><b>{p.name}</b><small>{p.province}</small></span><span>{currency(p.budget)}</span><span>{spend}%</span><span>{p.physicalProgress}%</span><span className={d>15?'danger-text':''}>{d} pts</span></button>{detail?.type==='project'&&detail.key===p.id&&<InlineDetail detail={detail} close={()=>toggleProject(p)} toggleProject={toggleProject}/>}</React.Fragment>})}</div></section>}

function ContractorsView({data,loading,openContractor,detail,toggleProject}:any){if(loading)return <Loading/>;return <section className="card full-view"><div className="card-head"><div><h2>Contractor Performance</h2><p>Select a contractor to expand its complete portfolio directly below the record.</p></div><Users/></div><div className="record-list">{data.map((x:any)=><React.Fragment key={x.name}><button className={`horizontal-record ${detail?.type==='contractor'&&detail.key===x.name?'expanded-row':''}`} onClick={()=>openContractor(x.name)}><span><b>{x.name}</b><small>{currency(x.contractValue||0)} portfolio value</small></span><span><small>Projects</small><b>{x.projects}</b></span><span><small>Average health</small><b>{x.averageHealth}/100</b></span><span><small>Critical / At risk</small><b>{x.criticalProjects} / {x.atRiskProjects}</b></span><ChevronRight/></button>{detail?.type==='contractor'&&detail.key===x.name&&<InlineDetail detail={detail} close={()=>openContractor(x.name)} toggleProject={toggleProject}/>}</React.Fragment>)}</div></section>}

function RisksView({data,loading,projects,toggleProject,detail}:any){if(loading)return <Loading/>;return <section className="card full-view"><div className="card-head"><div><h2>Risks & Blockers</h2><p>Select a risk to show the complete project detail directly below.</p></div><AlertTriangle/></div><div className="record-list">{data.map((x:any)=>{const p=projects.find((p:Project)=>p.id===x.projectId);return <React.Fragment key={x.projectId}><button className={`horizontal-record ${detail?.type==='project'&&detail.key===x.projectId?'expanded-row':''}`} onClick={()=>p&&toggleProject(p)}><span><b>{x.projectName}</b><small>{x.primaryBlocker}</small></span><span><small>Open risks</small><b>{x.openRisks}</b></span><span><small>Evidence age</small><b>{x.evidenceAgeDays}d</b></span><span><small>Divergence</small><b>{x.financialPhysicalDivergence} pts</b></span><Status value={x.status}/></button>{p&&detail?.type==='project'&&detail.key===x.projectId&&<InlineDetail detail={detail} close={()=>toggleProject(p)} toggleProject={toggleProject}/>}</React.Fragment>})}</div></section>}

function RecoveryView({data,loading,projects,toggleProject,detail}:any){if(loading)return <Loading/>;return <section className="card full-view"><div className="card-head"><div><h2>Recovery Plans</h2><p>Select an action to expand its project directly below.</p></div><Activity/></div><div className="record-list">{data.map((x:any)=>{const p=projects.find((p:Project)=>p.id===x.projectId);return <React.Fragment key={x.id}><button className={`horizontal-record ${detail?.type==='project'&&detail.key===x.projectId?'expanded-row':''}`} onClick={()=>p&&toggleProject(p)}><span><b>{x.title}</b><small>{x.projectName}</small></span><span><small>Owner</small><b>{x.owner}</b></span><span><small>Due</small><b>{x.due}</b></span><span><small>Action status</small><b>{x.status}</b></span><Status value={x.projectStatus}/></button>{p&&detail?.type==='project'&&detail.key===x.projectId&&<InlineDetail detail={detail} close={()=>toggleProject(p)} toggleProject={toggleProject}/>}</React.Fragment>})}</div></section>}

function AuditView({data,loading}:any){if(loading)return <Loading/>;return <section className="card full-view"><div className="card-head"><div><h2>Audit & Governance</h2><p>Material project and AI-assisted actions.</p></div><ShieldCheck/></div><div className="audit-list">{data.map((x:any,i:number)=><div className="audit-row" key={i}><div><b>{x.action}</b><span>{x.record}</span></div><div><b>{x.user}</b><span>{x.role}</span></div><div><b>{new Date(x.at).toLocaleString()}</b><span>{x.aiAssisted?'AI-assisted':'Human action'}</span></div></div>)}</div></section>}
function UsageView({data,loading}:any){if(loading)return <Loading/>;return <section className="card full-view"><div className="card-head"><div><h2>Usage Logs</h2><p>Who used HomeFlow, when, and which actions they performed.</p></div><ClipboardList/></div><div className="audit-list">{data.map((x:any,i:number)=><div className="audit-row" key={i}><div><b>{x.user}</b><span>{x.email}</span></div><div><b>{x.action}</b><span>{x.target}</span></div><div><b>{x.role}</b><span>{new Date(x.at).toLocaleString()}</span></div></div>)}</div></section>}
function Loading(){return <section className="card full-view loading-view">Loading HomeFlow data…</section>}

function ChatPanel({messages,input,setInput,busy,provider,onSend,onQuick,onVoice,onClose,onStop,endRef}:any){return <aside className="copilot"><div className="copilot-head"><div><Bot/><div><b>HomeFlow Voice Copilot</b><span>Conversational · grounded · {provider==='openai'?'OpenAI':'rules fallback'}</span></div></div><button onClick={onClose}><X/></button></div><div className="chat conversation">{messages.map((m:ChatMsg,i:number)=><div key={i} className={`bubble ${m.role}`}>{m.text}</div>)}{busy&&<div className="bubble assistant typing">•••</div>}<div ref={endRef}/></div><div className="quick-prompts"><button onClick={()=>onQuick('What requires my attention today?')}>Today's priorities</button><button onClick={()=>onQuick('Which projects have the largest budget-to-progress gap?')}>Budget gaps</button><button onClick={()=>onQuick('Which contractors need management review?')}>Contractors</button></div><form onSubmit={(e)=>{e.preventDefault();onSend()}}><button type="button" className="mic-only" onClick={onVoice}><Mic size={17}/></button><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask HomeFlow anything…" autoFocus/><button type="submit" disabled={busy||!input.trim()}>Send</button><button type="button" className="mic-only" onClick={onStop}><VolumeX size={17}/></button></form></aside>}

function InlineDetail({detail,close,toggleProject}:any){const d=detail.data;return <section className="inline-detail"><div className="inline-detail-head"><div><p className="eyebrow">DETAILS</p><h2>{detail.title}</h2></div><button onClick={close} title="Close details"><X/></button></div>{detail.type==='project'&&<ProjectDetail p={d}/>} {detail.type==='province'&&<ProvinceDetail d={d} toggleProject={toggleProject}/>} {detail.type==='contractor'&&<ContractorDetail d={d} toggleProject={toggleProject}/>} {detail.type==='brief'&&<BriefDetail d={d}/>} {detail.type==='message'&&<div className="inline-detail-body"><p>{d.message}</p></div>}</section>}
function ProjectDetail({p}:{p:Project}){const spend=Math.round(p.expenditure/p.budget*100),gap=spend-p.physicalProgress;return <div className="inline-detail-body"><div className="drawer-status"><Status value={p.status}/><span>Health {p.healthScore}/100</span><span>{p.province}</span><span>{p.stage}</span></div><div className="detail-grid horizontal"><Info label="Project ID" value={p.id}/><Info label="Programme" value={p.programme}/><Info label="Municipality" value={p.municipality}/><Info label="Ward" value={p.ward}/><Info label="Project manager" value={p.projectManager}/><Info label="Implementing agent" value={p.implementingAgent}/><Info label="Contractor" value={p.contractor}/><Info label="Start date" value={p.startDate}/><Info label="Forecast completion" value={p.forecastCompletion}/></div><h3>Delivery performance</h3><div className="detail-kpis horizontal"><Info label="Budget" value={currency(p.budget)}/><Info label="Expenditure" value={`${currency(p.expenditure)} (${spend}%)`}/><Info label="Physical progress" value={`${p.physicalProgress}%`}/><Info label="Planned progress" value={`${p.plannedProgress}%`}/><Info label="Budget/progress gap" value={`${gap} pts`}/><Info label="Units completed" value={`${p.unitsCompleted}/${p.unitsPlanned}`}/></div><div className="detail-columns"><div><h3>Risk & evidence</h3><div className="callout danger-callout"><b>{p.primaryBlocker}</b><span>{p.openRisks} open risks · {p.overdueMilestones} overdue milestones · evidence {p.evidenceAgeDays} days old</span></div>{p.rootCauses.length>0&&<ul>{p.rootCauses.map(x=><li key={x}>{x}</li>)}</ul>}</div><div><h3>Recovery actions</h3>{p.recoveryActions.length?p.recoveryActions.map(a=><div className="action-row" key={a.id}><div><b>{a.title}</b><span>{a.owner}</span></div><div><b>{a.status}</b><span>Due {a.due}</span></div></div>):<p className="muted">No active recovery plan is required.</p>}</div></div></div>}
function ProvinceDetail({d,toggleProject}:any){return <div className="inline-detail-body"><div className="detail-kpis horizontal"><Info label="Projects" value={d.summary.projects}/><Info label="Average health" value={`${d.summary.averageHealth}/100`}/><Info label="Critical" value={d.summary.critical}/><Info label="At risk" value={d.summary.atRisk}/><Info label="Units completed" value={`${d.summary.unitsCompleted}/${d.summary.unitsPlanned}`}/><Info label="Budget" value={currency(d.summary.budget)}/></div><h3>Projects in {d.name}</h3><div className="nested-records">{d.projects.map((p:Project)=><button className="nested-project" key={p.id} onClick={()=>toggleProject(p)}><span><b>{p.name}</b><small>{p.municipality} · {p.contractor}</small></span><strong>{p.healthScore}/100</strong><Status value={p.status}/></button>)}</div></div>}
function ContractorDetail({d,toggleProject}:any){return <div className="inline-detail-body"><div className="detail-kpis horizontal"><Info label="Projects" value={d.summary.projects}/><Info label="Average health" value={`${d.summary.averageHealth}/100`}/><Info label="Critical" value={d.summary.critical}/><Info label="At risk" value={d.summary.atRisk}/><Info label="Units completed" value={d.summary.unitsCompleted}/><Info label="Portfolio value" value={currency(d.summary.contractValue)}/></div><h3>Assigned projects</h3><div className="nested-records">{d.projects.map((p:Project)=><button className="nested-project" key={p.id} onClick={()=>toggleProject(p)}><span><b>{p.name}</b><small>{p.province} · {p.municipality}</small></span><strong>{p.healthScore}/100</strong><Status value={p.status}/></button>)}</div></div>}
function BriefDetail({d}:any){return <div className="inline-detail-body"><div className="brief-lead">{d.summary}</div><h3>Priority projects</h3><div className="priority-grid">{(d.priorities||[]).map((x:any)=><div className="priority-row" key={x.id}><div><b>{x.name}</b><span>{x.province} · {x.status}</span></div><strong>{x.score}/100</strong><p>{x.reason}</p></div>)}</div><h3>Decisions required</h3><ul>{(d.decisions||[]).map((x:string,i:number)=><li key={i}>{x}</li>)}</ul><p className="muted">{d.note}</p></div>}

function SettingsPanel({apiKey,setApiKey,model,setModel,autoSpeak,setAutoSpeak,connection,message,test,close}:any){return <div className="settings-backdrop" onClick={close}><section className="settings-panel settings-centred" onClick={e=>e.stopPropagation()}><div className="drawer-head"><div><p className="eyebrow">ADMINISTRATOR ONLY</p><h2>AI & Voice Settings</h2></div><button onClick={close}><X/></button></div><div className="drawer-body"><p className="muted">OpenAI configuration is restricted to the Administrator role. Keys are retained only for this browser session in hackathon mode.</p><label className="field">OpenAI API key<input type="password" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder="sk-…"/></label><label className="field">AI model<select value={model} onChange={e=>setModel(e.target.value)}><option value="gpt-5.6-luna">GPT-5.6 Luna</option><option value="gpt-5.6-terra">GPT-5.6 Terra</option><option value="gpt-5.6-sol">GPT-5.6 Sol</option></select></label><label className="toggle"><input type="checkbox" checked={autoSpeak} onChange={e=>setAutoSpeak(e.target.checked)}/><span>Automatically play humanlike spoken responses</span></label><button className="primary" onClick={test}><KeyRound size={16}/> Test OpenAI connection</button><div className={`connection ${connection}`}>{message||'Connection not tested.'}</div><div className="security-note"><ShieldCheck/><span>For production, move the OpenAI credential to Azure Key Vault or a server-side Render secret. Do not commit API keys to GitHub.</span></div></div></section></div>}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
