import './risk-page-fix.css';

type Project={id:string;name:string;province:string;municipality:string;contractor:string;status:string;healthScore:number;budget:number;expenditure:number;physicalProgress:number;plannedProgress:number;openRisks:number;overdueMilestones:number;evidenceAgeDays:number;forecastCompletion:string;primaryBlocker:string;rootCauses:string[]};
type Risk={projectId:string;projectName:string;province:string;municipality:string;openRisks:number;status:string;healthScore:number;primaryBlocker:string;rootCauses:string[];evidenceAgeDays:number;financialPhysicalDivergence:number;overdueMilestones:number;trend:string;forecastCompletion:string};
const API=import.meta.env.VITE_API_URL||(import.meta.env.PROD?'':'http://localhost:8080');
const token=()=>sessionStorage.getItem('homeflow_token')||'';
const headers=()=>({Authorization:`Bearer ${token()}`});
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
const money=(n:number)=>new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR',maximumFractionDigits:0}).format(n||0);
const slug=(s:string)=>s.toLowerCase().replace(/\s+/g,'-');
const isRiskPage=()=>document.querySelector('main header h1')?.textContent?.trim()==='Risks & Blockers';
let host:HTMLElement|null=null;
let timer:number|undefined;
let loadSeq=0;

async function get<T>(path:string):Promise<T>{const r=await fetch(`${API}${path}`,{headers:headers()});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error((b as any)?.error||`Request failed (${r.status})`);return b as T}
function remove(){host?.remove();host=null;document.querySelectorAll<HTMLElement>('main section.card.full-view').forEach(s=>{if(s.querySelector('.card-head h2')?.textContent?.trim()==='Risks & Blockers')s.style.display=''})}
function mount(){if(!isRiskPage()||!token()){remove();return null}const main=document.querySelector('main.main,main') as HTMLElement|null;if(!main)return null;if(host?.isConnected)return host;host=document.createElement('section');host.className='hf-risk-stable';const header=main.querySelector(':scope > header');if(header)header.insertAdjacentElement('afterend',host);else main.prepend(host);document.querySelectorAll<HTMLElement>('main section.card.full-view').forEach(s=>{if(s.querySelector('.card-head h2')?.textContent?.trim()==='Risks & Blockers')s.style.display='none'});return host}
function detail(r:Risk,p?:Project){const spend=p&&p.budget?Math.round(p.expenditure/p.budget*100):null;return `<div class="hf-risk-detail-inline" data-risk-detail="${esc(r.projectId)}" hidden><div><span>Province</span><b>${esc(r.province)}</b></div><div><span>Municipality</span><b>${esc(r.municipality)}</b></div><div><span>Health score</span><b>${esc(r.healthScore)}/100</b></div><div><span>Delivery trend</span><b>${esc(r.trend||'Not recorded')}</b></div><div><span>Open risks</span><b>${esc(r.openRisks)}</b></div><div><span>Overdue milestones</span><b>${esc(r.overdueMilestones||0)}</b></div><div><span>Evidence age</span><b>${esc(r.evidenceAgeDays)} days</b></div><div><span>Forecast completion</span><b>${esc(r.forecastCompletion||'Not recorded')}</b></div><div><span>Budget vs progress gap</span><b>${esc(r.financialPhysicalDivergence)} points</b></div><div><span>Contractor</span><b>${esc(p?.contractor||'Not recorded')}</b></div><div><span>Physical progress</span><b>${p?`${esc(p.physicalProgress)}%`:'Not recorded'}</b></div><div><span>Expenditure</span><b>${p&&spend!==null?`${money(p.expenditure)} (${spend}%)`:'Not recorded'}</b></div><div class="wide"><span>Primary blocker</span><b>${esc(r.primaryBlocker||'Not recorded')}</b></div><div class="wide"><span>Root causes</span><b>${esc(Array.isArray(r.rootCauses)&&r.rootCauses.length?r.rootCauses.join(', '):'Not recorded')}</b></div></div>`}
function render(risks:Risk[],projects:Project[]){const h=mount();if(!h)return;const projectMap=new Map(projects.map(p=>[p.id,p]));const total=risks.reduce((s,r)=>s+r.openRisks,0);const critical=risks.filter(r=>r.status==='Critical').length;const atRisk=risks.filter(r=>r.status==='At Risk').length;const overdue=risks.reduce((s,r)=>s+(r.overdueMilestones||0),0);const stale=risks.filter(r=>r.evidenceAgeDays>14).length;h.innerHTML=`<div class="hf-risk-stable-head"><div><h2>Risks & Blockers</h2><p>Live risk register for projects visible to your role. Select a record to drill down below it.</p></div><label class="hf-risk-search"><span>Search</span><input type="search" placeholder="Project, province or blocker" aria-label="Search risks and blockers"></label></div><div class="hf-risk-summary"><div><span>Risk records</span><strong>${risks.length}</strong></div><div><span>Open risks</span><strong>${total}</strong></div><div><span>Critical projects</span><strong>${critical}</strong></div><div><span>At risk projects</span><strong>${atRisk}</strong></div><div><span>Overdue milestones</span><strong>${overdue}</strong></div></div><div class="hf-risk-table"><div class="hf-risk-row-head"><span>Project</span><span>Primary blocker</span><span>Health</span><span>Open risks</span><span>Evidence</span><span>Status</span><span></span></div><div data-risk-list></div></div>${!risks.length?'<div class="hf-risk-empty">No active risks or blockers are visible to your role.</div>':''}`;
 const list=h.querySelector('[data-risk-list]') as HTMLElement;
 function draw(filter=''){list.innerHTML='';const q=filter.trim().toLowerCase();const rows=risks.filter(r=>!q||`${r.projectName} ${r.province} ${r.municipality} ${r.primaryBlocker} ${(r.rootCauses||[]).join(' ')}`.toLowerCase().includes(q));if(!rows.length){list.innerHTML='<div class="hf-risk-empty">No matching risks or blockers.</div>';return}for(const r of rows){const p=projectMap.get(r.projectId);const wrap=document.createElement('div');wrap.dataset.riskId=r.projectId;wrap.innerHTML=`<button class="hf-risk-row" type="button" aria-expanded="false"><span class="hf-risk-project"><b>${esc(r.projectName)}</b><small>${esc(r.province)} · ${esc(r.municipality)}</small></span><span class="hf-risk-blocker">${esc(r.primaryBlocker)}</span><span class="hf-risk-num">${esc(r.healthScore)}/100</span><span class="hf-risk-num">${esc(r.openRisks)}</span><span>${esc(r.evidenceAgeDays)}d</span><span class="hf-risk-status ${slug(r.status)}">${esc(r.status)}</span><span class="hf-risk-chevron">›</span></button>${detail(r,p)}`;const btn=wrap.querySelector('button')!;const d=wrap.querySelector('[data-risk-detail]') as HTMLElement;btn.addEventListener('click',()=>{const open=d.hidden;list.querySelectorAll<HTMLElement>('[data-risk-detail]').forEach(x=>x.hidden=true);list.querySelectorAll<HTMLButtonElement>('.hf-risk-row').forEach(x=>{x.classList.remove('expanded');x.setAttribute('aria-expanded','false')});d.hidden=!open;if(open){btn.classList.add('expanded');btn.setAttribute('aria-expanded','true');btn.scrollIntoView({block:'nearest'})}});list.appendChild(wrap)}}
 draw();(h.querySelector('input') as HTMLInputElement)?.addEventListener('input',e=>draw((e.target as HTMLInputElement).value));
}
async function load(){const seq=++loadSeq;if(!isRiskPage()||!token()){remove();return}const h=mount();if(!h)return;h.innerHTML='<div class="hf-risk-empty">Loading risk register…</div>';try{const [risks,projects]=await Promise.all([get<Risk[]>('/api/risks'),get<Project[]>('/api/projects')]);if(seq!==loadSeq||!isRiskPage())return;render(Array.isArray(risks)?risks:[],Array.isArray(projects)?projects:[])}catch(e:any){if(seq!==loadSeq||!isRiskPage())return;const m=mount();if(!m)return;m.innerHTML=`<div class="hf-risk-error"><b>Risks & Blockers could not be loaded.</b><p>${esc(e?.message||'Please try again.')}</p><button class="hf-risk-retry" type="button">Retry</button></div>`;m.querySelector('button')?.addEventListener('click',load)}}
function refresh(){window.clearTimeout(timer);timer=window.setTimeout(()=>{if(isRiskPage()){if(!host?.isConnected||!host.dataset.loaded){if(host)host.dataset.loaded='1';load()}}else{loadSeq++;remove()}},60)}
const observer=new MutationObserver(refresh);observer.observe(document.getElementById('root')||document.documentElement,{subtree:true,childList:true,characterData:true});window.addEventListener('load',refresh);setTimeout(refresh,250);
