import './smart-enhancements.css';

type Project={id:string;name:string;province:string;municipality:string;contractor:string;programme:string;status:string;healthScore:number;budget:number;expenditure:number;physicalProgress:number;plannedProgress:number;unitsPlanned:number;unitsCompleted:number;overdueMilestones:number;openRisks:number;evidenceAgeDays:number;forecastCompletion:string;primaryBlocker:string;trend:string;rootCauses:string[];projectManager:string;implementingAgent:string;stage:string;startDate:string;recoveryActions:any[]};
type Row=Record<string,any>;
const API=import.meta.env.VITE_API_URL||(import.meta.env.PROD?'':'http://localhost:8080');
const token=()=>sessionStorage.getItem('homeflow_token')||'';
const auth=()=>({Authorization:`Bearer ${token()}`,'Content-Type':'application/json'});
const esc=(v:any)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
const title=()=>document.querySelector('main header h1')?.textContent?.trim()||'';
async function api(path:string,init?:RequestInit){const r=await fetch(`${API}${path}`,{...init,headers:{...auth(),...(init?.headers||{})}});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body?.error||`Request failed (${r.status})`);return body;}
let projectsCache:Project[]|null=null;
async function projects(){if(projectsCache)return projectsCache;projectsCache=await api('/api/projects');return projectsCache||[];}
function main(){return document.querySelector('main.main,main') as HTMLElement|null}
function sectionAfterHeader(node:HTMLElement){const host=main();const header=host?.querySelector(':scope > header');if(header)header.insertAdjacentElement('afterend',node);else host?.prepend(node)}

function statusColor(status:string){return status==='Critical'?'#fb7185':status==='At Risk'?'#f59e0b':status==='Watch'?'#fbbf24':status==='Completed'?'#22c55e':'#38bdf8'}
function analyticsSvg(data:Array<{label:string,value:number,color:string,detail:string}>){const w=900,h=230,pad=42,max=Math.max(1,...data.map(d=>d.value));const step=(w-pad*2)/Math.max(data.length,1);const bars=data.map((d,i)=>{const bw=Math.max(22,step*.55),bh=(d.value/max)*(h-80),x=pad+i*step+(step-bw)/2,y=h-40-bh;return `<g class="bar" data-detail="${esc(d.detail)}"><rect x="${x}" y="${y}" width="${bw}" height="${bh}" rx="5" fill="${d.color}"/><text x="${x+bw/2}" y="${Math.max(16,y-7)}" text-anchor="middle" fill="#fff">${d.value}</text><text x="${x+bw/2}" y="${h-18}" text-anchor="middle">${esc(d.label.length>16?d.label.slice(0,14)+'…':d.label)}</text></g>`}).join('');return `<svg class="hf-chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="Interactive HomeFlow analytics chart"><line class="axis" x1="${pad}" y1="${h-40}" x2="${w-pad}" y2="${h-40}"/>${bars}</svg>`}
async function ensureAnalytics(){const page=title();if(!['Command Centre','Finance','Contractors','Risks & Blockers'].includes(page))return;const host=main();if(!host||host.querySelector('.hf-analytics-card'))return;const ps=await projects();if(!ps.length)return;const card=document.createElement('section');card.className='hf-analytics-card';card.innerHTML=`<div class="hf-section-head"><div><h2>Interactive delivery analytics</h2><p>Click a bar to inspect the underlying delivery indicator.</p></div><div class="hf-tabs"><button class="active" data-mode="status">Status</button><button data-mode="province">Province</button><button data-mode="variance">Budget vs progress</button></div></div><div class="hf-chart-wrap"></div><div class="hf-chart-detail">Select a bar to see more detail.</div>`;
 const wrap=card.querySelector('.hf-chart-wrap') as HTMLElement;const detail=card.querySelector('.hf-chart-detail') as HTMLElement;
 function render(mode:string){let data:Array<{label:string,value:number,color:string,detail:string}>=[];if(mode==='status'){for(const s of ['Critical','At Risk','Watch','Healthy','Completed']){const list=ps.filter(p=>p.status===s);data.push({label:s,value:list.length,color:statusColor(s),detail:`${list.length} ${s.toLowerCase()} projects: ${list.slice(0,6).map(p=>p.name).join(', ')||'none'}.`})}}else if(mode==='province'){for(const province of [...new Set(ps.map(p=>p.province))]){const list=ps.filter(p=>p.province===province);const risk=list.filter(p=>p.status==='Critical'||p.status==='At Risk').length;data.push({label:province,value:risk,color:risk>2?'#fb7185':risk?'#f59e0b':'#38bdf8',detail:`${province}: ${list.length} projects, ${risk} critical/at-risk, ${list.reduce((s,p)=>s+p.unitsCompleted,0).toLocaleString('en-ZA')} completed units.`})}}else{data=[...ps].sort((a,b)=>(b.expenditure/b.budget*100-b.physicalProgress)-(a.expenditure/a.budget*100-a.physicalProgress)).slice(0,10).map(p=>{const gap=Math.round(p.expenditure/p.budget*100)-p.physicalProgress;return{label:p.name,value:Math.max(0,gap),color:gap>20?'#fb7185':gap>10?'#f59e0b':'#38bdf8',detail:`${p.name}: ${Math.round(p.expenditure/p.budget*100)}% spent versus ${p.physicalProgress}% physical progress, ${gap} point divergence.`}})}wrap.innerHTML=analyticsSvg(data);wrap.querySelectorAll('.bar').forEach(b=>b.addEventListener('click',()=>detail.textContent=(b as HTMLElement).dataset.detail||''));}
 card.querySelectorAll('.hf-tabs button').forEach(b=>b.addEventListener('click',()=>{card.querySelectorAll('.hf-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render((b as HTMLElement).dataset.mode||'status')}));render('status');
 const metrics=host.querySelector('.metrics');if(page==='Command Centre'&&metrics)metrics.insertAdjacentElement('afterend',card);else sectionAfterHeader(card);
}

async function ensureRiskView(){if(title()!=='Risks & Blockers')return;const host=main();if(!host||host.querySelector('.hf-risk-v2'))return;const risks=await api('/api/risks');const card=document.createElement('section');card.className='hf-risk-v2';card.innerHTML=`<div class="hf-section-head"><div><h2>Risks & blockers</h2><p>${risks.length} active project risk records. Expand a record for delivery detail.</p></div><button class="hf-action-btn" data-send-risk>Send early-risk alert</button></div><div class="hf-risk-grid"></div>`;const grid=card.querySelector('.hf-risk-grid') as HTMLElement;if(!risks.length)grid.innerHTML='<p>No active risks are visible to your role.</p>';for(const x of risks){const item=document.createElement('article');item.className='hf-risk-item';item.innerHTML=`<button type="button"><div class="hf-risk-top"><strong>${esc(x.projectName)}</strong><span class="hf-severity">${esc(x.status)}</span></div><p>${esc(x.primaryBlocker)}</p><div class="hf-risk-meta">${x.openRisks} open risks · ${x.overdueMilestones||0} overdue milestones · evidence ${x.evidenceAgeDays} days old</div></button><div class="hf-risk-detail" hidden><div><span>Province</span><b>${esc(x.province)}</b></div><div><span>Municipality</span><b>${esc(x.municipality)}</b></div><div><span>Health</span><b>${esc(x.healthScore)}/100</b></div><div><span>Budget gap</span><b>${esc(x.financialPhysicalDivergence)} pts</b></div><div><span>Trend</span><b>${esc(x.trend||'—')}</b></div><div><span>Forecast</span><b>${esc(x.forecastCompletion||'—')}</b></div><div style="grid-column:span 2"><span>Root causes</span><b>${esc(Array.isArray(x.rootCauses)?x.rootCauses.join(', '):x.rootCauses||'Not recorded')}</b></div></div>`;const btn=item.querySelector('button')!;const d=item.querySelector('.hf-risk-detail') as HTMLElement;btn.addEventListener('click',()=>{d.hidden=!d.hidden});grid.appendChild(item)}card.querySelector('[data-send-risk]')?.addEventListener('click',sendRiskAlert);sectionAfterHeader(card);
 // Hide the original broken risk list, but keep the page header/navigation intact.
 [...host.querySelectorAll('section.card')].forEach(s=>{if(s!==card&&/Risks & Blockers/i.test(s.textContent||''))(s as HTMLElement).style.display='none'});
}

function dayPct(start:string,end:string){const s=new Date(start+'T00:00:00Z').getTime(),e=new Date(end+'T00:00:00Z').getTime(),n=Date.now();if(!Number.isFinite(s)||!Number.isFinite(e)||e<=s)return 0;return Math.max(0,Math.min(100,(n-s)/(e-s)*100))}
async function ensureGantt(){if(title()!=='Projects')return;const host=main();if(!host||host.querySelector('.hf-gantt-card'))return;const ps=await projects();const ordered=[...ps].sort((a,b)=>a.healthScore-b.healthScore).slice(0,16);const card=document.createElement('section');card.className='hf-gantt-card';card.innerHTML=`<div class="hf-section-head"><div><h2>Project schedule / Gantt monitoring</h2><p>Portfolio schedule view based on project start, forecast completion, planned progress and verified physical progress.</p></div></div><div class="hf-gantt"><div class="hf-gantt-grid"><div class="hf-gantt-head"><span>Project</span><span>Start</span><span>Forecast</span><span>Progress against plan</span><span>Status</span></div>${ordered.map(p=>{const today=dayPct(p.startDate,p.forecastCompletion);const planned=Math.max(0,Math.min(100,p.plannedProgress));const actual=Math.max(0,Math.min(100,p.physicalProgress));const bad=actual+5<planned;return `<div class="hf-gantt-row" data-project="${esc(p.id)}"><div><div class="hf-gantt-name">${esc(p.name)}</div><div class="hf-gantt-dates">${p.overdueMilestones} overdue milestones</div></div><div class="hf-gantt-dates">${esc(p.startDate)}</div><div class="hf-gantt-dates">${esc(p.forecastCompletion)}</div><div class="hf-track" title="Actual ${actual}% · Planned ${planned}%"><div class="hf-plan" style="width:${planned}%"></div><div class="hf-actual ${bad?'bad':''}" style="width:${actual}%"></div><div class="hf-marker" style="left:${today}%" title="Today"></div></div><div class="hf-gantt-status">${esc(p.status)}</div></div>`}).join('')}</div></div><div class="hf-chart-detail">Blue/rose = verified physical progress · shaded = planned progress · yellow line = today within the project schedule.</div>`;sectionAfterHeader(card);
}

async function ensureControlPack(){if(title()!=='Projects')return;const host=main();if(!host||host.querySelector('.hf-control-pack'))return;const ps=await projects();const due=ps.reduce((s,p)=>s+p.overdueMilestones,0);const critical=ps.filter(p=>p.status==='Critical').length;const stale=ps.filter(p=>p.evidenceAgeDays>14).length;const recoveries=ps.reduce((s,p)=>s+(p.recoveryActions?.length||0),0);const card=document.createElement('section');card.className='hf-control-pack';card.innerHTML=`<div class="hf-section-head"><div><h2>Project management control pack</h2><p>Core controls beyond status reporting: schedule, RAID, recovery, evidence, contractor and decision management.</p></div></div><div class="hf-control-grid"><div class="hf-control-tile"><span>Schedule control</span><strong>${due} overdue milestones</strong></div><div class="hf-control-tile"><span>RAID / critical risks</span><strong>${critical} critical projects</strong></div><div class="hf-control-tile"><span>Evidence assurance</span><strong>${stale} projects with stale evidence</strong></div><div class="hf-control-tile"><span>Recovery actions</span><strong>${recoveries} active actions</strong></div><div class="hf-control-tile"><span>Dependency control</span><strong>Primary blockers tracked per project</strong></div><div class="hf-control-tile"><span>Cost & schedule variance</span><strong>Budget-progress divergence monitored</strong></div><div class="hf-control-tile"><span>Decision & audit trail</span><strong>Usage and governance logs enabled</strong></div><div class="hf-control-tile"><span>Early warning</span><strong>Proactive risk thresholds enabled</strong></div></div>`;const gantt=host.querySelector('.hf-gantt-card');if(gantt)gantt.insertAdjacentElement('afterend',card);else sectionAfterHeader(card)}

async function reportRows():Promise<Row[]>{const page=title();if(page==='Risks & Blockers')return api('/api/risks');if(page==='Recovery Plans')return api('/api/recovery');if(page==='Contractors')return api('/api/contractors');if(page==='Audit & Governance')return api('/api/audit');if(page==='Usage Logs')return api('/api/usage-logs');return api('/api/projects')}
async function emailReport(){try{const rows=await reportRows();const b=await api('/api/notifications/report',{method:'POST',body:JSON.stringify({title:title()||'HomeFlow AI report',rows:rows.slice(0,120)})});alert(`Report sent to ${b.recipient}.`)}catch(e:any){alert(e?.message||'Unable to email report.')}}
async function sendRiskAlert(){try{const b=await api('/api/notifications/send-alerts',{method:'POST',body:'{}'});alert(`Risk alert sent to ${b.recipient}.`)}catch(e:any){alert(e?.message||'Unable to send risk alert.')}}
function ensureEmailButton(){const actions=document.querySelector('.header-actions');if(!actions||actions.querySelector('[data-hf-email-report]'))return;const btn=document.createElement('button');btn.className='ghost hf-report-email';btn.dataset.hfEmailReport='1';btn.textContent='Email report';btn.title='Email the current report to samson@pyrneo.com';btn.addEventListener('click',emailReport);actions.appendChild(btn)}

// Replace robotic browser TTS with server-side natural TTS when OpenAI voice is available.
let naturalAudio:HTMLAudioElement|null=null;
function installNaturalVoice(){const synth=window.speechSynthesis as any;if(!synth||synth.__homeflowNaturalVoice)return;synth.__homeflowNaturalVoice=true;const nativeSpeak=synth.speak.bind(synth);const nativeCancel=synth.cancel.bind(synth);synth.speak=(utterance:SpeechSynthesisUtterance)=>{const text=String(utterance?.text||'').trim();if(!text)return;const language=utterance.lang||localStorage.getItem('homeflow_voice_lang')||'en-ZA';const headers:any=auth();const key=sessionStorage.getItem('homeflow_openai_key');if(key)headers['x-openai-api-key']=key;fetch(`${API}/api/voice/speak`,{method:'POST',headers,body:JSON.stringify({text,language})}).then(async r=>{if(!r.ok)throw new Error('natural voice unavailable');const blob=await r.blob();if(naturalAudio){naturalAudio.pause();naturalAudio=null}const url=URL.createObjectURL(blob);const a=new Audio(url);naturalAudio=a;a.onended=()=>{URL.revokeObjectURL(url);naturalAudio=null};await a.play()}).catch(()=>nativeSpeak(utterance))};synth.cancel=()=>{if(naturalAudio){naturalAudio.pause();naturalAudio.src='';naturalAudio=null}nativeCancel()}}

async function ensureAlertStrip(){if(title()!=='Command Centre')return;const host=main();if(!host||host.querySelector('.hf-alert-strip'))return;try{const d=await api('/api/alerts');const top=d.warnings?.[0];if(!top)return;const strip=document.createElement('div');strip.className='hf-alert-strip';strip.innerHTML=`<div><strong>Early warning:</strong> ${esc(top.projectName)} — ${esc(top.signals?.slice(0,2).join(', '))}</div><button class="hf-action-btn" type="button">Review risks</button>`;strip.querySelector('button')?.addEventListener('click',()=>{const nav=[...document.querySelectorAll('button')].find(b=>/Risks & Blockers/i.test(b.textContent||'')) as HTMLButtonElement|null;nav?.click()});const metrics=host.querySelector('.metrics');if(metrics)metrics.insertAdjacentElement('afterend',strip);else sectionAfterHeader(strip)}catch{}}

let timer:number|undefined;
async function enhance(){if(!token())return;installNaturalVoice();ensureEmailButton();try{await ensureRiskView();await ensureAnalytics();await ensureGantt();await ensureControlPack();await ensureAlertStrip()}catch(e){console.warn('HomeFlow enhancement warning',e)}}
const observer=new MutationObserver(()=>{clearTimeout(timer);timer=window.setTimeout(enhance,120)});observer.observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('load',enhance);setTimeout(enhance,400);
