import './smart-enhancements.css';

type Project={id:string;name:string;province:string;municipality:string;contractor:string;programme:string;status:string;healthScore:number;budget:number;expenditure:number;physicalProgress:number;plannedProgress:number;unitsPlanned:number;unitsCompleted:number;overdueMilestones:number;openRisks:number;evidenceAgeDays:number;forecastCompletion:string;primaryBlocker:string;trend:string;rootCauses:string[];projectManager:string;implementingAgent:string;stage:string;startDate:string;recoveryActions:any[]};
const API=import.meta.env.VITE_API_URL||(import.meta.env.PROD?'':'http://localhost:8080');
const token=()=>sessionStorage.getItem('homeflow_token')||'';
const auth=()=>({Authorization:`Bearer ${token()}`,'Content-Type':'application/json'});
const esc=(v:any)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
async function api(path:string,init?:RequestInit){const r=await fetch(`${API}${path}`,{...init,headers:{...auth(),...(init?.headers||{})}});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body?.error||`Request failed (${r.status})`);return body}
let projectCache:Project[]|null=null;
async function projects(){if(projectCache)return projectCache;projectCache=await api('/api/projects');return projectCache||[]}
function pageName(){const eyebrow=document.querySelector('main header .eyebrow')?.textContent?.trim()||'';if(/COMMAND CENTRE/i.test(eyebrow))return'Command Centre';return document.querySelector('main header h1')?.textContent?.trim()||''}

// ---- Natural voice bridge -------------------------------------------------
let naturalAudio:HTMLAudioElement|null=null;
function bestBrowserVoice(lang:string){if(!('speechSynthesis'in window))return null;const voices=speechSynthesis.getVoices();const base=lang.split('-')[0].toLowerCase();const exact=voices.filter(v=>v.lang.toLowerCase()===lang.toLowerCase());const related=voices.filter(v=>v.lang.toLowerCase().startsWith(base));const natural=(v:SpeechSynthesisVoice)=>/(natural|online|neural|premium|enhanced|leah|ayanda|zanele|thando|zira|aria|samantha|karen|google|microsoft)/i.test(v.name);return exact.find(natural)||related.find(natural)||exact[0]||related[0]||voices.find(v=>v.lang.toLowerCase().endsWith('-za')&&natural(v))||voices.find(natural)||null}
function installNaturalVoice(){const synth=window.speechSynthesis as any;if(!synth||synth.__hfNaturalBridge)return;synth.__hfNaturalBridge=true;const nativeSpeak=synth.speak.bind(synth);const nativeCancel=synth.cancel.bind(synth);synth.speak=(utterance:SpeechSynthesisUtterance)=>{const text=String(utterance?.text||'').trim();if(!text)return;const language=utterance.lang||localStorage.getItem('homeflow_voice_lang')||'en-ZA';const headers:any=auth();const key=sessionStorage.getItem('homeflow_openai_key');if(key)headers['x-openai-api-key']=key;fetch(`${API}/api/voice/speak`,{method:'POST',headers,body:JSON.stringify({text,language})}).then(async r=>{if(!r.ok)throw new Error('Natural voice service unavailable');const blob=await r.blob();if(naturalAudio){naturalAudio.pause();naturalAudio.src='';naturalAudio=null}const url=URL.createObjectURL(blob);const a=new Audio(url);naturalAudio=a;a.onended=()=>{URL.revokeObjectURL(url);naturalAudio=null};await a.play()}).catch(()=>{const preferred=bestBrowserVoice(language);if(preferred)utterance.voice=preferred;utterance.lang=language;utterance.rate=.96;utterance.pitch=1;nativeSpeak(utterance)})};synth.cancel=()=>{if(naturalAudio){naturalAudio.pause();naturalAudio.src='';naturalAudio=null}nativeCancel()}}

// ---- Navigation-safe smart tools -----------------------------------------
let shell:HTMLElement|null=null,drawer:HTMLElement|null=null,lastPage='';
function ensureShell(){if(shell?.isConnected)return shell;shell=document.createElement('div');shell.id='hf-smart-tools';shell.innerHTML='<div class="hf-smart-dock" aria-label="HomeFlow smart tools"></div><aside class="hf-smart-drawer" aria-live="polite" hidden></aside>';document.body.appendChild(shell);drawer=shell.querySelector('.hf-smart-drawer');return shell}
function closeDrawer(){if(drawer){drawer.hidden=true;drawer.innerHTML=''}}
function dock(){return ensureShell().querySelector('.hf-smart-dock') as HTMLElement}
function button(label:string,action:()=>void,title?:string){const b=document.createElement('button');b.type='button';b.textContent=label;b.title=title||label;b.addEventListener('click',action);return b}
function renderDock(){if(!token()){ensureShell().style.display='none';return}ensureShell().style.display='block';const page=pageName();if(page!==lastPage){lastPage=page;closeDrawer()}const d=dock();d.innerHTML='';if(['Command Centre','Finance','Contractors','Risks & Blockers'].includes(page))d.appendChild(button('Analytics',()=>openAnalytics(page),'Open interactive delivery analytics'));if(page==='Projects')d.appendChild(button('Gantt',openGantt,'Open portfolio Gantt monitoring'));d.appendChild(button('Email report',emailReport,'Email the current page report to samson@pyrneo.com'))}
function openDrawer(title:string,subtitle:string,body:string){ensureShell();if(!drawer)return;drawer.innerHTML=`<div class="hf-smart-head"><div><strong>${esc(title)}</strong><span>${esc(subtitle)}</span></div><button type="button" aria-label="Close smart tool">×</button></div><div class="hf-smart-body">${body}</div>`;drawer.hidden=false;drawer.querySelector('button')?.addEventListener('click',closeDrawer)}
function color(status:string){return status==='Critical'?'#fb7185':status==='At Risk'?'#f59e0b':status==='Watch'?'#fbbf24':status==='Completed'?'#22c55e':'#38bdf8'}
function chartSvg(data:Array<{label:string,value:number,color:string,detail:string}>){const w=820,h=250,pad=42,max=Math.max(1,...data.map(d=>d.value));const step=(w-pad*2)/Math.max(data.length,1);return `<svg class="hf-smart-chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="HomeFlow interactive analytics">${data.map((d,i)=>{const bw=Math.max(20,step*.56),bh=(d.value/max)*(h-85),x=pad+i*step+(step-bw)/2,y=h-42-bh;return `<g class="hf-smart-bar" tabindex="0" data-detail="${esc(d.detail)}"><rect x="${x}" y="${y}" width="${bw}" height="${bh}" rx="5" fill="${d.color}"/><text x="${x+bw/2}" y="${Math.max(18,y-7)}" text-anchor="middle">${d.value}</text><text x="${x+bw/2}" y="${h-18}" text-anchor="middle">${esc(d.label.length>14?d.label.slice(0,12)+'…':d.label)}</text></g>`}).join('')}</svg><div class="hf-smart-detail">Select a bar to inspect the underlying projects.</div>`}
async function openAnalytics(page:string){try{const ps=await projects();const groups=['Critical','At Risk','Watch','Healthy','Completed'].map(s=>{const list=ps.filter(p=>p.status===s);return{label:s,value:list.length,color:color(s),detail:`${list.length} ${s.toLowerCase()} projects: ${list.slice(0,7).map(p=>p.name).join(', ')||'none'}.`}});openDrawer(`${page} analytics`,'Interactive delivery status analysis',chartSvg(groups));drawer?.querySelectorAll('.hf-smart-bar').forEach(el=>{const activate=()=>{const detail=drawer?.querySelector('.hf-smart-detail');if(detail)detail.textContent=(el as HTMLElement).dataset.detail||''};el.addEventListener('click',activate);el.addEventListener('keydown',(e:any)=>{if(e.key==='Enter'||e.key===' ')activate()})})}catch(e:any){openDrawer('Analytics unavailable','Please try again',`<p>${esc(e?.message||'Unable to load analytics.')}</p>`)}}
function pct(start:string,end:string){const s=new Date(start+'T00:00:00Z').getTime(),e=new Date(end+'T00:00:00Z').getTime(),n=Date.now();if(!Number.isFinite(s)||!Number.isFinite(e)||e<=s)return 0;return Math.max(0,Math.min(100,(n-s)/(e-s)*100))}
async function openGantt(){try{const ps=[...(await projects())].sort((a,b)=>a.healthScore-b.healthScore).slice(0,20);const rows=ps.map(p=>{const planned=Math.max(0,Math.min(100,p.plannedProgress)),actual=Math.max(0,Math.min(100,p.physicalProgress)),today=pct(p.startDate,p.forecastCompletion);return `<div class="hf-smart-gantt-row"><div><b>${esc(p.name)}</b><span>${p.overdueMilestones} overdue milestones</span></div><small>${esc(p.startDate)}</small><small>${esc(p.forecastCompletion)}</small><div class="hf-smart-track"><i class="plan" style="width:${planned}%"></i><i class="actual ${actual+5<planned?'bad':''}" style="width:${actual}%"></i><i class="today" style="left:${today}%"></i></div><em>${esc(p.status)}</em></div>`}).join('');openDrawer('Project Gantt monitoring','Planned vs verified delivery progress',`<div class="hf-smart-gantt-head"><span>Project</span><span>Start</span><span>Forecast</span><span>Progress vs plan</span><span>Status</span></div>${rows}<div class="hf-smart-legend">Blue/rose = verified physical progress · shaded = planned progress · yellow line = today.</div>`)}catch(e:any){openDrawer('Gantt unavailable','Please try again',`<p>${esc(e?.message||'Unable to load Gantt.')}</p>`)}}
async function reportRows(){const page=pageName();if(page==='Risks & Blockers')return api('/api/risks');if(page==='Recovery Plans')return api('/api/recovery');if(page==='Contractors')return api('/api/contractors');if(page==='Audit & Governance')return api('/api/audit');if(page==='Usage Logs')return api('/api/usage-logs');return api('/api/projects')}
async function emailReport(){try{const rows=await reportRows();const b=await api('/api/notifications/report',{method:'POST',body:JSON.stringify({title:pageName()||'HomeFlow AI report',rows:rows.slice(0,120)})});openDrawer('Report queued',`Recipient: ${b.recipient}`,`<p>The current ${esc(pageName())} report was submitted for email delivery.</p>`)}catch(e:any){openDrawer('Email unavailable','Report could not be sent',`<p>${esc(e?.message||'Unable to email report.')}</p>`)}}

let timer:number|undefined;
function refresh(){installNaturalVoice();window.clearTimeout(timer);timer=window.setTimeout(renderDock,80)}
const observer=new MutationObserver(refresh);observer.observe(document.getElementById('root')||document.documentElement,{subtree:true,childList:true,characterData:true});
window.addEventListener('load',refresh);setTimeout(refresh,250);
